### ISSUE TITLE
The app returns just 30 repositories

### ISSUE THREAD

**Issue by devmousa** [MasterMousa/Github-Profiles-Search#1]
This website will return only 30 repos when you search for a profiles
## how to fix it:
-make _prev_ and _next_ buttons
-there is _page_ query for github api, change the page number using the previous buttons
-you can find the file in **profile** folder inside **components** folder which also inside **src** folder

**Comment by mohammedzeglam-pg** [comment]
is any work on it?

**Comment by devmousa** [comment]
I fixed it by infinite scroll and it's working well right now
